(() => {
"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const products=(window.MENU_PRODUCTS||[]).map(p=>({...p,veg:!/(chicken|mutton|fish|egg|katla|rui|prawn|meat)/i.test(p.name)}));
const categories={starters:["🍢","Starters"],tandoor:["🔥","Tandoor"],noodles:["🍜","Noodles"],chinese:["🥢","Chinese"],soup:["🥣","Soups"],seafood:["🐟","Seafood"],combo:["🍛","Combos"],veg:["🥦","Vegetarian"],roti:["🫓","Breads"],biryani:["🍚","Biryani"],rice:["🍚","Rice & Mains"],salad:["🥗","Salads & Drinks"]};
const order=["starters","tandoor","noodles","chinese","soup","seafood","combo","veg","roti","biryani","rice","salad"],popular=[30,86,24,43,20,52,88,41,84,44];
const KEY="savor_cafe_cart_v2"; let cart=JSON.parse(localStorage.getItem(KEY)||"{}"),activeCategory="all",currentMode="delivery";
const money=n=>`₹${Number(n).toLocaleString("en-IN")}`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(cart));
const count=()=>Object.values(cart).reduce((a,b)=>a+b,0);
const total=()=>Object.entries(cart).reduce((s,[id,q])=>s+(products.find(p=>p.id==id)?.price||0)*q,0);
function stepper(id){return `<div class="stepper"><button type="button" data-minus="${id}">−</button><b>${cart[id]||0}</b><button type="button" data-plus="${id}">+</button></div>`}
function add(id){cart[id]=(cart[id]||0)+1;save();renderAll();toast(`${products.find(p=>p.id===id)?.name||"Item"} added to cart ✓`)}
function change(id,d){cart[id]=Math.max(0,(cart[id]||0)+d);if(!cart[id])delete cart[id];save();renderAll()}
function toast(t){let e=$("#toast");if(!e)return;e.textContent=t;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),1800)}
function renderNav(){const n=count(),t=total();["#cartCount","#navCartCount"].forEach(s=>{if($(s))$(s).textContent=n});let bar=$("#viewCartBar");if(bar){bar.hidden=n===0;bar.classList.toggle("show",n>0);if($("#floatingCartCount"))$("#floatingCartCount").textContent=`${n} ${n===1?"item":"items"}`;if($("#floatingCartTotal"))$("#floatingCartTotal").textContent=money(t)}}
function renderHome(){const c=$("#homeCats");if(c)c.innerHTML=order.map(k=>`<a class="category-card" href="/menu.html?category=${k}"><span class="emoji">${categories[k][0]}</span><h3>${categories[k][1]}</h3><p>${products.filter(p=>p.category===k).length} dishes</p></a>`).join("");const p=$("#homePopular");if(p)p.innerHTML=popular.map(id=>{let x=products.find(a=>a.id===id);return x?`<article class="popular-card"><div class="food-art">${emoji(x)}</div><h3>${esc(x.name)}</h3><div class="pc-bottom"><strong>${money(x.price)}</strong><button class="mini-add" data-add="${x.id}">+ Add</button></div></article>`:""}).join("")}
function emoji(p){if(!p)return"🍽️";if(/biryani|rice|khichuri|pulao/i.test(p.name))return"🍚";if(/noodle|manchurian|chilli|fried rice/i.test(p.name))return"🍜";if(/fish|katla|rui|prawn/i.test(p.name))return"🐟";if(/paneer|veg|dal|aloo|mushroom|broccoli|rajma|roti|naan|paratha/i.test(p.name))return"🥘";return"🍗"}
function renderMenu(){const mount=$("#menuMount");if(!mount)return;const q=($("#search")?.value||"").trim().toLowerCase(),groups=activeCategory==="all"?order:[activeCategory];let html="",seen=0;groups.forEach(k=>{let list=products.filter(p=>p.category===k&&(!q||p.name.toLowerCase().includes(q)));if(!list.length)return;seen+=list.length;html+=`<section class="menu-section" id="cat-${k}"><h2>${categories[k][0]} ${categories[k][1]} <span>${list.length} dishes</span></h2><div class="menu-grid">${list.map(p=>`<article class="menu-item"><div class="item-info"><i class="food-dot ${p.veg?"":"nonveg"}"></i><div><div class="item-name">${esc(p.name)}</div><div class="item-price">${money(p.price)}</div></div></div>${cart[p.id]?stepper(p.id):`<button class="add-button" data-add="${p.id}">+ Add</button>`}</article>`).join("")}</div></section>`});mount.innerHTML=html;if($("#emptyState"))$("#emptyState").hidden=seen!==0}
function renderTabs(){let e=$("#cats");if(!e)return;e.innerHTML=`<button class="category-tab ${activeCategory==="all"?"active":""}" data-cat="all">All</button>`+order.map(k=>`<button class="category-tab ${activeCategory===k?"active":""}" data-cat="${k}">${categories[k][0]} ${categories[k][1]}</button>`).join("")}
function renderCartPage(){let box=$("#cartPageItems");if(!box)return;let ids=Object.keys(cart).map(Number);box.innerHTML=ids.length?ids.map(id=>{let p=products.find(x=>x.id===id);return p?`<div class="cart-page-line"><div><b>${esc(p.name)}</b><small>${money(p.price)} each</small></div><div><strong>${money(p.price*(cart[id]||0))}</strong>${stepper(id)}<button class="remove" data-remove="${id}">Remove</button></div></div>`:""}).join(""):`<div class="cart-empty"><div>🛒</div><h2>Your cart is empty</h2><p>Add some dishes first.</p><a class="btn primary" href="/menu.html">Browse menu →</a></div>`;if($("#cartPageTotal"))$("#cartPageTotal").textContent=money(total());if($("#checkoutBtn"))$("#checkoutBtn").classList.toggle("disabled",!ids.length)}
function renderCheckout(){let box=$("#checkoutItems");if(!box)return;let ids=Object.keys(cart).map(Number);if(!ids.length){box.innerHTML=`<div class="checkout-empty">Your cart is empty.<br><a href="/menu.html">Browse menu →</a></div>`;$("#checkoutTotal").textContent="₹0";$("#checkoutForm")?.querySelector("button[type=submit]")?.setAttribute("disabled","");return}box.innerHTML=ids.map(id=>{let p=products.find(x=>x.id===id);return p?`<div class="summary-line"><span>${esc(p.name)} <b>× ${cart[id]}</b></span><strong>${money(p.price*cart[id])}</strong></div>`:""}).join("");$("#checkoutTotal").textContent=money(total())}
function renderAll(){renderNav();renderHome();renderTabs();renderMenu();renderCartPage();renderCheckout()}
function status(){let m=new Date().getHours()*60+new Date().getMinutes(),o=m>=660&&m<1380;if($("#statusText"))$("#statusText").textContent=o?"Open now":"Closed · Opens 11 AM";if($("#statusDot"))$("#statusDot").classList.toggle("closed",!o)}
function checkoutUrl(fd){let items=Object.entries(cart).map(([id,q])=>{let p=products.find(x=>x.id==id);return`• ${p.name} × ${q} = ${money(p.price*q)}`}).join("\n"),mode=currentMode==="delivery"?"Delivery":currentMode==="takeaway"?"Takeaway":"Dine-in";let text=`*SAVOR CAFE' — NEW ORDER*\n\n*Order type:* ${mode}\n*Name:* ${fd.get("name")}\n*Phone:* ${fd.get("phone")}\n`;if(currentMode==="delivery")text+=`*Address:* ${fd.get("address")}\n`;text+=`\n*Items:*\n${items}\n\n*Total:* ${money(total())}`;if(fd.get("notes"))text+=`\n*Notes:* ${fd.get("notes")}`;return`https://wa.me/918981315889?text=${encodeURIComponent(text)}`}
function themeInit(){let saved=localStorage.getItem("savor_theme")||"dark";document.documentElement.dataset.theme=saved;let b=$("#themeToggle");if(b){b.textContent=saved==="dark"?"☀️":"🌙";b.title=saved==="dark"?"Switch to light mode":"Switch to dark mode";b.setAttribute("aria-label",b.title)}}
function setup(){themeInit();const toggle=$("#navToggle"),links=$("#navLinks"),scrim=$("#navScrim");function close(){links?.classList.remove("open");scrim?.classList.remove("show");toggle?.setAttribute("aria-expanded","false");if(toggle)toggle.textContent="☰";document.body.classList.remove("nav-lock")}toggle?.addEventListener("click",()=>{links.classList.contains("open")?close():(links.classList.add("open"),scrim.classList.add("show"),toggle.setAttribute("aria-expanded","true"),toggle.textContent="✕",document.body.classList.add("nav-lock"))});scrim?.addEventListener("click",close);links?.querySelectorAll("a").forEach(a=>a.addEventListener("click",close));
let page=location.pathname.split("/").pop().replace(".html","")||"index";page=page==="index"?"home":page;$$('.nav-links a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));if($("#statusText"))status();setInterval(status,60000);const params=new URLSearchParams(location.search);if(params.get("category"))activeCategory=params.get("category");renderAll();
$("#themeToggle")?.addEventListener("click",()=>{let next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("savor_theme",next);let b=$("#themeToggle");b.textContent=next==="dark"?"☀️":"🌙";b.title=next==="dark"?"Switch to light mode":"Switch to dark mode";b.setAttribute("aria-label",b.title)});
document.addEventListener("click",e=>{let a=e.target.closest("[data-add]"),pl=e.target.closest("[data-plus]"),mi=e.target.closest("[data-minus]"),rm=e.target.closest("[data-remove]"),cat=e.target.closest("[data-cat]");if(a)add(+a.dataset.add);else if(pl)change(+pl.dataset.plus,1);else if(mi)change(+mi.dataset.minus,-1);else if(rm){delete cart[rm.dataset.remove];save();renderAll()}else if(cat){activeCategory=cat.dataset.cat;renderTabs();renderMenu()}});
$("#search")?.addEventListener("input",()=>{if($("#searchClear"))$("#searchClear").classList.toggle("show",!!$("#search").value);renderMenu()});$("#searchClear")?.addEventListener("click",()=>{$("#search").value="";$("#searchClear").classList.remove("show");renderMenu()});
$$("#orderMode button").forEach(b=>b.addEventListener("click",()=>{$$("#orderMode button").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentMode=b.dataset.mode;if($("#addressWrap"))$("#addressWrap").style.display=currentMode==="delivery"?"":"none"}));
$("#gpsBtn")?.addEventListener("click",()=>navigator.geolocation?.getCurrentPosition(p=>{$("textarea[name=address]").value=`https://www.google.com/maps?q=${p.coords.latitude},${p.coords.longitude}`;$("#gpsMsg").textContent="Location added."},()=>$("#gpsMsg").textContent="Could not access location."));
$("#checkoutForm")?.addEventListener("submit",e=>{e.preventDefault();if(!count())return toast("Your cart is empty");window.location.href=checkoutUrl(new FormData(e.currentTarget))});
$("#contactForm")?.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(e.currentTarget);window.open(`https://wa.me/918981315889?text=${encodeURIComponent(`Hello Savor Cafe'!\n\nName: ${f.get("name")}\nPhone: ${f.get("phone")||"Not provided"}\nMessage: ${f.get("message")}`)}`,"_blank")});
const pl=$("#preloader");if(pl){if(sessionStorage.getItem("savor_intro_seen")){pl.classList.add("hide")}else{sessionStorage.setItem("savor_intro_seen","1");setTimeout(()=>pl.classList.add("hide"),1300)}}
}
document.addEventListener("DOMContentLoaded",setup);
})();